force-app/main/default/objects/Warship__c/Warship__c.object-meta.xml
<CustomObject>
    <label>Warship</label>
    <nameField>
        <label>Warship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warships</relationshipLabel>
    <relationshipName>Warships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warship__c/fields/ActiveMilestones__c.field-meta.xml
<CustomField>
    <fullName>ActiveMilestones__c</fullName>
    <label>Active Milestones</label>
    <summaryFilterItems>
        <field>Milestone__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Complete</value>
    </summaryFilterItems>
    <summaryForeignKey>Milestone__c.Warship__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Warship__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warship__c/fields/Weapons_Status__c.field-meta.xml
<CustomField>
    <fullName>Weapons_Status__c</fullName>
    <label>Weapons Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Operational</fullName>
            </value>
            <value>
                <fullName>Fully Operacional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerListWarship.cls
public class ControllerListWarship {

    public ControllerListWarship() {
        init();
    }


    public List<Warship__c> warship{ get; set; }

    private void init(){      
        String userName = UserInfo.getUserName();
        User activeUser = [Select Email From User where Username = : userName limit 1];
        Contact contact = [Select id, email, Account.Name, isResponsibleForComunication__c from contact where email = :activeUser.Email and isResponsibleForComunication__c = true];

        warship = [Select id, Name, ActiveMilestones__c, Project_Status__c, Weapons_Status__c from Warship__c where account__r.Name = :contact.Account.Name];
    }
}
 