force-app/main/default/objects/Milestone__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due_Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Warship__c.field-meta.xml
<CustomField>
    <fullName>Warship__c</fullName>
    <label>Warship</label>
    <referenceTo>Warship__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warship__c/Warship__c.object-meta.xml
<CustomObject>
    <label>Warship</label>
    <nameField>
        <label>Warship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warship_Supply__c/Warship_Supply__c.object-meta.xml
<CustomObject>
    <label>Warship_Supply</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Warship_Supply  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WarshipSupplies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warship_Supply__c/fields/Ship_supply__c.field-meta.xml
<CustomField>
    <fullName>Ship_supply__c</fullName>
    <label>Ship</label>
    <referenceTo>Warship__c</referenceTo>
    <relationshipName>Warship_Supplies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warship_Supply__c/fields/Supply_Name__c.field-meta.xml
<CustomField>
    <fullName>Supply_Name__c</fullName>
    <formula>Supply__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supply Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/lwc_ManegementWarships.cls
/**
 * @description       : 
 * @author            : Fábio Marques
 * @group             : 
 * @last modified on  : 18-07-2022
 * @last modified by  : Fábio Marques
**/
public with sharing class lwc_ManegementWarships {
    @AuraEnabled(cacheable=true)
    public static List<Warship__c> getWarships() {
       return [
            SELECT Id, Name
            FROM Warship__c
       ];
       
    }

    @AuraEnabled
    public static List<Warship_Supply__c> getSupllies(String wId) {
     try {
          List<Warship_Supply__c> supplies = [ SELECT Id, Name, Supply_Name__c, Quantity__c FROM Warship_Supply__c WHERE Ship_supply__c = :wId Order by Supply_Name__c];
          if(supplies.isEmpty()){
               return null;
               }
               return supplies;
     } catch (Exception e) {
          throw new AuraHandledException(e.getMessage());
     } 
     }

     @AuraEnabled
    public static List<Milestone__c> getMilestones(String wId) {
     try {
          List<Milestone__c> milestones = [SELECT id, Name, Due_Date__c,Status__c  FROM Milestone__c WHERE Warship__c = :wId Order by Due_Date__c];
          if(milestones.isEmpty()){
               return null;
               }
               return milestones;
     } catch (Exception e) {
          throw new AuraHandledException(e.getMessage());
     } 
     }

}