force-app/main/default/objects/Milestone__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due_Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/check_Due_Date.cls
/**
 * @description       : 
 * @author            : Fábio Marques
 * @group             : 
 * @last modified on  : 21-07-2022
 * @last modified by  : Fábio Marques
**/
public class check_Due_Date implements Schedulable {
    
    public void execute(SchedulableContext sc){
        
        List<Milestone__c> m = [SELECT id, Due_Date__c, Status__c FROM Milestone__c Where Status__c != 'Complete'];

        for(Milestone__c ms : m){         
            if((ms.Due_Date__c) < System.today()){
                ms.Status__c = 'Behind Schedule';            
            }  
        }
        update m;
    }
} 