force-app/main/default/objects/Milestone__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due_Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Milestone_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBatchDueDate.cls
/**
 * @description       : 
 * @author            : Fábio Marques
 * @group             : 
 * @last modified on  : 21-07-2022
 * @last modified by  : Fábio Marques
**/
@isTest
public class TestBatchDueDate {
    @TestSetup
    static void makeData(){
        TestDataFactory.createWarshipsWithMilestones();
    }

    @isTest
    static void checkStatusMilestone(){
        Test.startTest();
        BatchDueDate batchable = new BatchDueDate();     
        Database.executeBatch(batchable);
        Test.stopTest();

        List<Milestone__c> milestones = [SELECT id, Name,Due_Date__c, Status__c From Milestone__c];

        for (Milestone__c m : milestones) {
            if((m.Due_Date__c) < System.today()){
                System.assertEquals('Behind Schedule', m.Status__c, 'Should have changed it to Behind Schedule');
            }
        } 
    }
}