force-app/main/default/objects/Milestone__c/fields/Warship__c.field-meta.xml
<CustomField>
    <fullName>Warship__c</fullName>
    <label>Warship</label>
    <referenceTo>Warship__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warship__c/Warship__c.object-meta.xml
<CustomObject>
    <label>Warship</label>
    <nameField>
        <label>Warship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warships</relationshipLabel>
    <relationshipName>Warships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warship__c/fields/ActiveMilestones__c.field-meta.xml
<CustomField>
    <fullName>ActiveMilestones__c</fullName>
    <label>Active Milestones</label>
    <summaryFilterItems>
        <field>Milestone__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Complete</value>
    </summaryFilterItems>
    <summaryForeignKey>Milestone__c.Warship__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Warship__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warship__c/fields/Weapons_Status__c.field-meta.xml
<CustomField>
    <fullName>Weapons_Status__c</fullName>
    <label>Weapons Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Operational</fullName>
            </value>
            <value>
                <fullName>Fully Operacional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warship_Resource__c/Warship_Resource__c.object-meta.xml
<CustomObject>
    <label>WarshipResource</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Warship_Resource__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WarshipsResources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warship_Resource__c/fields/Warship__c.field-meta.xml
<CustomField>
    <fullName>Warship__c</fullName>
    <label>Warship</label>
    <referenceTo>Warship__c</referenceTo>
    <relationshipLabel>WarshipsResources</relationshipLabel>
    <relationshipName>WarshipsResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warship_Supply__c/Warship_Supply__c.object-meta.xml
<CustomObject>
    <label>Warship_Supply</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Warship_Supply  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WarshipSupplies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Warship_Supply__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <formula>Supply__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warship_Supply__c/fields/Ship_supply__c.field-meta.xml
<CustomField>
    <fullName>Ship_supply__c</fullName>
    <label>Ship</label>
    <referenceTo>Warship__c</referenceTo>
    <relationshipName>Warship_Supplies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warship_Supply__c/fields/Supply_Name__c.field-meta.xml
<CustomField>
    <fullName>Supply_Name__c</fullName>
    <formula>Supply__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supply Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/lwc_ManegementWarshipsTest.cls
/**
 * @description       : 
 * @author            : Fábio Marques
 * @group             : 
 * @last modified on  : 21-07-2022
 * @last modified by  : Fábio Marques
**/
@isTest
public class lwc_ManegementWarshipsTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createWarSup(5);
        TestDataFactory.createWarRes(5);
    } 

    @isTest
    static void testGetWarships(){     
        Test.startTest();
        List<Warship__c> warships = lwc_ManegementWarships.getWarships();
        Test.stopTest();
        System.assertEquals(2, warships.size());
    }

    @isTest
    static void testGetSupllies(){
        List<Warship_Supply__c> w_Id = [Select id, Ship_supply__c From Warship_Supply__c Limit 1];
        Test.startTest();
        List<Warship_Supply__c> supplies = lwc_ManegementWarships.getSupllies(w_Id[0].Ship_supply__c);
        List<Warship_Supply__c> suppliesNull = lwc_ManegementWarships.getSupllies(w_Id[0].Id);   
        Test.stopTest();
        System.assertEquals(null, suppliesNull);
        System.assertEquals(5, supplies.size());
    }

    @isTest
    static void testGetMilestones(){
        List<Warship__c> warships = [Select id from Warship__c limit 2];
        TestDataFactory.createMilestones(warships[0].Id, 5);
        Test.startTest();
        List<Milestone__c> milestonesNull = lwc_ManegementWarships.getMilestones(warships[1].Id);
        List<Milestone__c> milestones = lwc_ManegementWarships.getMilestones(warships[0].Id);   
        Test.stopTest();
        System.assertEquals(null, milestonesNull);
        System.assertEquals(5, milestones.size());
    }

    @isTest
    static void testGetAddSupply(){
        List<Warship_Supply__c> warSup = [Select Id,Supply_Name__c, Quantity__c, Available_Quantity__c FROM Warship_Supply__c limit 1 ];
        Test.startTest();
        Warship_Supply__c getWarsup = lwc_ManegementWarships.getAddSupply(warSup[0].Id); 
        Test.stopTest();
        System.assertEquals(warSup[0], getWarsup);
    }

    @isTest
    static void testUpdateWarSup(){
        List<Warship_Supply__c> warSup = [Select Id,Supply_Name__c, Quantity__c, Available_Quantity__c FROM Warship_Supply__c limit 1 ];
        
        Test.startTest();
        List<Warship_Supply__c> getWarsup = lwc_ManegementWarships.updateWarSup(warSup[0].Id, 5); 
        Test.stopTest();

        for (Warship_Supply__c ws : getWarsup) {
            if (ws.Id == warSup[0].id) {
                System.assertEquals(warSup[0].Quantity__c + 5, ws.Quantity__c);
            }
        }
    }

    @isTest
    static void testGetDataWarship(){
        List<Warship__c> warship = [SELECT Id, Name, ActiveMilestones__c, Project_Status__c, Weapons_Status__c, Owner.Name, Account__r.Name FROM Warship__c];
        
        Test.startTest();
        Warship__c getWarship = lwc_ManegementWarships.getDataWarship(warship[0].Id); 
        Warship__c getWarshipNull = lwc_ManegementWarships.getDataWarship('5324632487'); 
        Test.stopTest();

        System.assertEquals(warship[0], getWarship);
        System.assertEquals(null, getWarshipNull);
    }

    @isTest
    static void testGetResources(){
        List<Warship_Resource__c> w_Id = [SELECT Id, Resource_Name__c,Warship__c, Quantity__c FROM Warship_Resource__c limit 1];

        Test.startTest();
        List<Warship_Resource__c> resources = lwc_ManegementWarships.getResources(w_Id[0].Warship__c);
        List<Warship_Resource__c> resourcesNull = lwc_ManegementWarships.getResources(w_Id[0].Id);   
        Test.stopTest();

        System.assertEquals(null, resourcesNull);
        System.assertEquals(5, resources.size());
    }
}